<input type="hidden" name="card_holder_name" value="{{auth()->user()->card_holder_name}}">
<input type="hidden" name="card_token" value="{{auth()->user()->card_token}}">
<input type="hidden" name="card_hash" value="{{auth()->user()->card_hash}}">
<input type="hidden" name="card_holder_document_type" value="{{auth()->user()->card_holder_document_type}}">
<input type="hidden" name="card_holder_document_value" value="{{auth()->user()->card_holder_document_value}}">
<input type="hidden" name="address_zip" value="{{auth()->user()->address_zip}}">
<input type="hidden" name="address_street" value="{{auth()->user()->address_street}}">
<input type="hidden" name="address_number" value="{{auth()->user()->address_number}}">
<input type="hidden" name="address_complement" value="{{auth()->user()->address_complement}}">
<input type="hidden" name="address_district" value="{{auth()->user()->address_district}}">
<input type="hidden" name="address_state" value="{{auth()->user()->address_state}}">
<input type="hidden" name="address_city" value="{{auth()->user()->address_city}}">